In [1]:
import pandas as pd


df_o1 = pd.read_csv("questbench_data/Planning-Q/planning_heldout_7500_o1_subsample.csv")
df_7500 = pd.read_csv("questbench_data/Planning-Q/planning_heldout_7500.csv")
df_prompts = pd.read_csv("questbench_data/Planning-Q/planning_heldout_prompts.csv")

In [2]:
df_o1.shape

(100, 9)

In [3]:
df_7500.shape

(7500, 9)

In [4]:
df_prompts.shape

(38, 9)

In [5]:
df_o1.head()

,conditions,goals,min_depth,plan_to_gt_q,gt_qs,all_valid_qs,all_qs,num_vars,check_time
0,(on b a)\n(clear f)\n(clear c)\n(on f d)\n(ont...,(on b a)\n(on d c),4,"{(<Op (stack d c)>, <Op (pick-up d)>, <Op (uns...",{'No questions needed.'},"['(clear b)', '(holding e)', '(on c b)', '(ont...","['(clear a)', '(clear b)', '(clear c)', '(clea...",6,0.005516
1,(on a b)\n(ontable b)\n(on d a)\n(clear d)\nno...,(on b a),4,"{(<Op (stack b a)>, <Op (pick-up b)>, <Op (uns...",{'No questions needed.'},"['(clear c)', '(handempty)', '(ontable c)']","['(clear a)', '(clear b)', '(clear c)', '(clea...",4,0.000442
2,(on e a)\n(clear b)\n(handempty)\n(clear e)\nn...,(on b a),4,"{(<Op (unstack e a)>, <Op (put-down e)>, <Op (...","frozenset({'(on b c)', '(clear c)', '(on a c)'...","['(clear c)', '(clear d)', '(on a c)', '(on a ...","['(clear a)', '(clear b)', '(clear c)', '(clea...",5,0.010813
3,(handempty)\n(clear c)\n(on c d)\n(ontable b)\...,(on b a)\n(on c b),4,"{(<Op (stack c b)>, <Op (unstack c d)>, <Op (s...",{'No questions needed.'},"['(clear b)', '(ontable a)', '(ontable d)']","['(clear a)', '(clear b)', '(clear c)', '(clea...",4,0.000379
4,(clear a)\n(on f b)\n(on b e)\n(clear f)\nnot ...,(on b a),4,"{(<Op (stack b a)>, <Op (unstack b e)>, <Op (u...",{'No questions needed.'},"['(clear d)', '(holding c)', '(on a d)', '(on ...","['(clear a)', '(clear b)', '(clear c)', '(clea...",6,0.021293

In [6]:
df_7500.head()

,conditions,goals,min_depth,plan_to_gt_q,gt_qs,all_valid_qs,all_qs,num_vars,check_time
0,(on c a)\n(clear c)\n(ontable a)\n(clear b)\n(...,(on b a)\n(on c b)\n(ontable a),6,"{(<Op (unstack c a)>, <Op (put-down c)>, <Op (...","frozenset({'(handempty)', '(ontable d)', '(cle...","['(clear d)', '(handempty)', '(holding d)', '(...","['(clear a)', '(clear b)', '(clear c)', '(clea...",5,0.005872
1,(on c a)\n(clear c)\n(ontable a)\n(clear b)\n(...,(on b a)\n(on c b)\n(ontable a),7,"{(<Op (stack c b)>, <Op (pick-up c)>, <Op (sta...",{'No questions needed.'},"['(holding d)', '(ontable e)']","['(clear a)', '(clear b)', '(clear c)', '(clea...",5,0.002722
2,(on c a)\n(clear c)\n(ontable a)\n(clear b)\n(...,(on b a)\n(on c b)\n(ontable a),6,"{(<Op (stack c b)>, <Op (pick-up c)>, <Op (sta...",{'No questions needed.'},"['(clear d)', '(handempty)', '(on e d)', '(ont...","['(clear a)', '(clear b)', '(clear c)', '(clea...",5,0.003331
3,(on a c)\n(ontable b)\n(clear a)\n(holding d)\...,(on b a)\n(on c b)\n(ontable a),7,"{(<Op (put-down d)>, <Op (unstack a c)>, <Op (...","frozenset({'(clear b)', '(ontable e)', '(on e ...","['(clear b)', '(on e b)', '(ontable e)']","['(clear a)', '(clear b)', '(clear c)', '(clea...",5,0.006877
4,(on a c)\n(ontable b)\n(clear a)\n(holding d)\...,(on b a)\n(on c b)\n(ontable a),7,"{(<Op (stack c b)>, <Op (unstack c e)>, <Op (s...",{'No questions needed.'},"['(clear b)', '(ontable e)']","['(clear a)', '(clear b)', '(clear c)', '(clea...",5,0.001664

In [7]:
df_o1.head()

,conditions,goals,min_depth,plan_to_gt_q,gt_qs,all_valid_qs,all_qs,num_vars,check_time
0,(on b a)\n(clear f)\n(clear c)\n(on f d)\n(ont...,(on b a)\n(on d c),4,"{(<Op (stack d c)>, <Op (pick-up d)>, <Op (uns...",{'No questions needed.'},"['(clear b)', '(holding e)', '(on c b)', '(ont...","['(clear a)', '(clear b)', '(clear c)', '(clea...",6,0.005516
1,(on a b)\n(ontable b)\n(on d a)\n(clear d)\nno...,(on b a),4,"{(<Op (stack b a)>, <Op (pick-up b)>, <Op (uns...",{'No questions needed.'},"['(clear c)', '(handempty)', '(ontable c)']","['(clear a)', '(clear b)', '(clear c)', '(clea...",4,0.000442
2,(on e a)\n(clear b)\n(handempty)\n(clear e)\nn...,(on b a),4,"{(<Op (unstack e a)>, <Op (put-down e)>, <Op (...","frozenset({'(on b c)', '(clear c)', '(on a c)'...","['(clear c)', '(clear d)', '(on a c)', '(on a ...","['(clear a)', '(clear b)', '(clear c)', '(clea...",5,0.010813
3,(handempty)\n(clear c)\n(on c d)\n(ontable b)\...,(on b a)\n(on c b),4,"{(<Op (stack c b)>, <Op (unstack c d)>, <Op (s...",{'No questions needed.'},"['(clear b)', '(ontable a)', '(ontable d)']","['(clear a)', '(clear b)', '(clear c)', '(clea...",4,0.000379
4,(clear a)\n(on f b)\n(on b e)\n(clear f)\nnot ...,(on b a),4,"{(<Op (stack b a)>, <Op (unstack b e)>, <Op (u...",{'No questions needed.'},"['(clear d)', '(holding c)', '(on a d)', '(on ...","['(clear a)', '(clear b)', '(clear c)', '(clea...",6,0.021293

In [8]:
df_1000_o1 = pd.read_csv("questbench_data/Logic-Q/simplelogic_heldout_1k_o1_subsample.csv")
df_1000_prompts = pd.read_csv("questbench_data/Logic-Q/simplelogic_heldout_1k_prompts.csv")
df_1000 = pd.read_csv("questbench_data/Logic-Q/simplelogic_heldout_1k.csv")

In [9]:
df_1000_o1.shape

(100, 14)

In [10]:
df_1000_prompts.shape

(25, 14)

In [11]:
df_1000.shape

(1150, 14)

In [12]:
df_1000_o1.head()

,known_facts,known_untrue_facts,cannot_ask_facts,goal,rules,max_depth,min_num_rules_needed,num_constraints,num_vars,all_qs,all_valid_qs,gt_qs,gt_q_to_true_derivation,gt_q_to_false_derivation
0,"['clumsy', 'frail', 'long']",[],"['amused', 'bossy', 'cruel', 'cute', 'disguste...",enchanting,"[['amused', 'not clumsy', 'not disgusted'], ['...",2,2,31,22,"{'cruel', 'bossy', 'cute', 'frail', 'long', 'c...","{'frail', 'long', 'clumsy', 'enchanting', 'nau...",['naughty'],"{'naughty': [[['frail', 'long', 'cute'], 'ench...","{'naughty': [[['not cute'], 'not enchanting'],..."
1,['difficult'],[],['innocent'],grumpy,"[['difficult', 'not grumpy', 'not innocent', '...",2,2,11,10,"{'shy', 'innocent', 'old-fashioned', 'grumpy',...","{'grumpy', 'shy', 'difficult', 'old-fashioned'}",['old-fashioned'],"{'old-fashioned': [[['old-fashioned'], 'grumpy...","{'old-fashioned': [[['not innocent'], 'not gru..."
2,"['calm', 'difficult']",[],[],vivacious,"[['busy', 'not calm', 'not difficult', 'not po...",2,2,15,20,"{'silly', 'vivacious', 'impatient', 'calm', 'g...","{'silly', 'vivacious', 'impatient', 'calm', 'g...","['busy', 'powerful']","{'powerful': [[['busy'], 'vivacious'], [['powe...","{'powerful': [[['not powerful'], 'not vivaciou..."
3,['thoughtful'],[],[],cruel,"[['bright', 'not cruel', 'not loving', 'not pr...",2,2,28,25,"{'cruel', 'ugliest', 'embarrassed', 'vivacious...","{'cruel', 'ugliest', 'embarrassed', 'vivacious...","['bright', 'embarrassed']","{'bright': [[['embarrassed', 'thoughtful', 'fr...","{'bright': [[['thoughtful', 'not bright'], 'no..."
4,['smart'],[],[],agreeable,"[['agreeable', 'not amused'], ['agreeable', 'n...",2,2,16,20,"{'different', 'disobedient', 'agreeable', 'ner...","{'different', 'agreeable', 'disobedient', 'ner...","['amused', 'attentive', 'dull']","{'amused': [[['amused'], 'agreeable']], 'dull'...","{'amused': [[['not attentive', 'smart'], 'not ..."

In [13]:
df_1000_prompts.head()

,known_facts,known_untrue_facts,cannot_ask_facts,goal,rules,max_depth,min_num_rules_needed,num_constraints,num_vars,all_qs,all_valid_qs,gt_qs,gt_q_to_true_derivation,gt_q_to_false_derivation
0,"['amused', 'dull', 'worried']",[],"['excited', 'quaint']",messy,"[['agreeable', 'not amused', 'not messy', 'not...",3,4,71,43,"{'grumpy', 'frail', 'nervous', 'gleaming', 'du...","{'grumpy', 'gleaming', 'frantic', 'mysterious'...","['calm', 'dishonest', 'excited', 'frantic', 'g...","{'dishonest': [[['helpless', 'dishonest'], 'me...","{'dishonest': [[['dull', 'amused', 'not quaint..."
1,[],[],[],shy,"[['aggressive', 'not calm', 'not gorgeous', 'n...",6,9,39,30,"{'stormy', 'shy', 'ugly', 'calm', 'pleasant', ...","{'stormy', 'shy', 'ugly', 'calm', 'pleasant', ...","['pleasant', 'quaint']","{'quaint': [[['aggressive', 'stormy'], 'shy'],...","{'quaint': [[['not quaint'], 'not shy']], 'ple..."
2,['lonely'],[],[],clumsy,"[['anxious', 'not difficult', 'not lonely', 'n...",3,4,64,41,"{'zealous', 'precious', 'spotless', 'difficult...","{'precious', 'difficult', 'perfect', 'busy', '...","['busy', 'diplomatic', 'excited', 'lucky', 'pe...","{'lucky': [[['fragile', 'excited', 'spotless']...","{'lucky': [[['not lucky'], 'not clumsy']], 'ex..."
3,"['hilarious', 'horrible', 'light', 'shiny']",[],"['beautiful', 'fearless', 'helpful', 'homely',...",hypocritical,"[['adorable', 'not beautiful', 'not gorgeous',...",7,9,66,46,"{'polite', 'good', 'wrong', 'horrible', 'beaut...","{'polite', 'silly', 'light', 'good', 'shiny', ...",['good'],"{'good': [[['gorgeous'], 'hypocritical'], [['s...","{'good': [[['not worried'], 'not hypocritical'..."
4,"['careless', 'friendly', 'gorgeous', 'messy', ...",[],[],enchanting,"[['ambitious', 'not comfortable', 'not crowded...",3,5,40,48,"{'ambitious', 'rational', 'confused', 'pleasan...","{'confused', 'thoughtless', 'comfortable', 'pe...","['ambitious', 'confident', 'plain', 'thoughtle...","{'ambitious': [[['plain'], 'enchanting'], [['f...","{'ambitious': [[['gorgeous', 'not thoughtless'..."

In [14]:
df_1000.head()

,known_facts,known_untrue_facts,cannot_ask_facts,goal,rules,max_depth,min_num_rules_needed,num_constraints,num_vars,all_qs,all_valid_qs,gt_qs,gt_q_to_true_derivation,gt_q_to_false_derivation
0,"['amused', 'calm', 'loving', 'sleepy']",[],['sensible'],tired,"[['aggressive', 'not elated', 'not supportive'...",6,9,65,53,"{'frightened', 'difficult', 'sensible', 'dull'...","{'frightened', 'difficult', 'loving', 'thought...","['different', 'frightened', 'hurt']","{'frightened': [[['different', 'shiny'], 'tire...","{'frightened': [[['not sensible'], 'not tired'..."
1,['loving'],[],"['comfortable', 'good', 'lonely', 'quaint', 'r...",combative,"[['attentive', 'not clumsy', 'not outrageous',...",5,7,101,55,"{'precious', 'spotless', 'impatient', 'good', ...","{'precious', 'impatient', 'difficult', 'loving...","['clumsy', 'frantic', 'outrageous', 'spotless'...","{'thoughtless': [[['spotless', 'frantic', 'hom...","{'thoughtless': [[['not silly'], 'not combativ..."
2,"['precious', 'spotless']",[],"['attentive', 'clumsy', 'comfortable', 'differ...",combative,"[['attentive', 'not clumsy', 'not outrageous',...",4,6,101,55,"{'precious', 'spotless', 'impatient', 'good', ...","{'precious', 'spotless', 'embarrassed', 'impat...","['different', 'loving', 'shy', 'tired']","{'shy': [[['thoughtless', 'nervous'], 'combati...","{'shy': [[['not silly'], 'not combative'], [['..."
3,"['difficult', 'spotless']",[],"['attentive', 'clumsy', 'comfortable', 'differ...",combative,"[['attentive', 'not clumsy', 'not outrageous',...",5,7,101,55,"{'precious', 'spotless', 'impatient', 'good', ...","{'precious', 'spotless', 'embarrassed', 'impat...","['different', 'loving', 'shy', 'tired']","{'shy': [[['thoughtless', 'nervous'], 'combati...","{'shy': [[['not silly'], 'not combative'], [['..."
4,['spotless'],[],"['comfortable', 'good', 'lonely', 'quaint', 'r...",combative,"[['attentive', 'not clumsy', 'not outrageous',...",4,5,101,55,"{'precious', 'spotless', 'impatient', 'good', ...","{'precious', 'impatient', 'difficult', 'loving...","['attentive', 'clumsy', 'different', 'frantic'...","{'lonely': [[['different', 'silly', 'unpleasan...","{'lonely': [[['not silly'], 'not combative'], ..."

In [15]:
df_csp_full_prompts = pd.read_csv("questbench_data/GSM-Q/gsm_CSP_full_prompts.csv")
df_csp_full = pd.read_csv("questbench_data/GSM-Q/gsm_CSP_full.csv")
df_csp_pilot_prompts = pd.read_csv("questbench_data/GSM-Q/gsm_CSP_heldout_pilot_prompts.csv")
df_csp_pilot = pd.read_csv("questbench_data/GSM-Q/gsm_CSP_heldout_pilot.csv")

df_verbal_full_prompts = pd.read_csv("questbench_data/GSM-Q/gsm_verbal_full_prompts.csv")
df_verbal_full = pd.read_csv("questbench_data/GSM-Q/gsm_verbal_full.csv")
df_verbal_pilot_prompts = pd.read_csv("questbench_data/GSM-Q/gsm_verbal_heldout_pilot_prompts.csv")
df_verbal_pilot = pd.read_csv("questbench_data/GSM-Q/gsm_verbal_heldout_pilot.csv")

In [16]:
df_csp_full_prompts.shape

(10, 14)

In [17]:
df_csp_full.shape

(6591, 14)

In [18]:
df_csp_pilot_prompts.shape

(25, 14)

In [19]:
df_csp_pilot.shape

(151, 14)

In [20]:
df_verbal_full_prompts.shape

(20, 11)

In [21]:
df_verbal_full.shape

(23642, 11)

In [22]:
df_verbal_pilot_prompts.shape

(25, 11)

In [23]:
df_verbal_pilot.shape

(288, 11)

In [24]:
df_csp_full_prompts.head()

,Question ID,Full Problem,CSP,Full Answer,GT Question,Heldout Value,Possible Questions,Distractor Vars,Rewritten Problem,Rewritten Problem Answer,Equations,Variables,Pred Values,depth
0,78,L = 1\nM = 1\nN = 45\nN1 = 40\nP1 = 10\nX = 2\...,Variables:\nE [Total earnings for the week]\nL...,460,N1,40.0,"[""N1"", ""X""]",['X'],E = (P1 * N1) + (P2 * N2) + (P1 * L)\nN2 = N -...,NaN,"{""N2 = N - N1"": ""The number of overtime hours ...","{""N1"": ""Number of regular hours worked"", ""P1"":...",N1 = 40\nP1 = 10\nN = 45\nM = 1\nX = 2\nL = 1\...,2
1,78,L = 1\nM = 1\nN = 45\nN1 = 40\nP1 = 10\nX = 2\...,Variables:\nE [Total earnings for the week]\nL...,460,P1,10.0,"[""P1"", ""X""]",['X'],E = (P1 * N1) + (P2 * N2) + (P1 * L)\nN2 = N -...,NaN,"{""N2 = N - N1"": ""The number of overtime hours ...","{""N1"": ""Number of regular hours worked"", ""P1"":...",N1 = 40\nP1 = 10\nN = 45\nM = 1\nX = 2\nL = 1\...,2
2,78,L = 1\nM = 1\nN = 45\nN1 = 40\nP1 = 10\nX = 2\...,Variables:\nE [Total earnings for the week]\nL...,460,N,45.0,"[""N"", ""X""]",['X'],E = (P1 * N1) + (P2 * N2) + (P1 * L)\nN2 = N -...,NaN,"{""N2 = N - N1"": ""The number of overtime hours ...","{""N1"": ""Number of regular hours worked"", ""P1"":...",N1 = 40\nP1 = 10\nN = 45\nM = 1\nX = 2\nL = 1\...,2
3,78,L = 1\nM = 1\nN = 45\nN1 = 40\nP1 = 10\nX = 2\...,Variables:\nE [Total earnings for the week]\nL...,460,M,1.0,"[""M"", ""X""]",['X'],E = (P1 * N1) + (P2 * N2) + (P1 * L)\nN2 = N -...,NaN,"{""N2 = N - N1"": ""The number of overtime hours ...","{""N1"": ""Number of regular hours worked"", ""P1"":...",N1 = 40\nP1 = 10\nN = 45\nM = 1\nX = 2\nL = 1\...,2
4,78,L = 1\nM = 1\nN = 45\nN1 = 40\nP1 = 10\nX = 2\...,Variables:\nE [Total earnings for the week]\nL...,460,L,1.0,"[""L"", ""X""]",['X'],E = (P1 * N1) + (P2 * N2) + (P1 * L)\nN2 = N -...,NaN,"{""N2 = N - N1"": ""The number of overtime hours ...","{""N1"": ""Number of regular hours worked"", ""P1"":...",N1 = 40\nP1 = 10\nN = 45\nM = 1\nX = 2\nL = 1\...,1

In [25]:
df_csp_full.head()

,Question ID,Full Problem,CSP,Full Answer,GT Question,Heldout Value,Possible Questions,Distractor Vars,Rewritten Problem,Rewritten Problem Answer,Equations,Variables,Pred Values,depth
0,1878,C1 = 20\nS1 = 6\nV1 = 3\nW = 7\nG1 = S1/2\nG2 ...,Variables:\nC1 = 20 [Number of cherries Steve ...,21,S1,6.0,"[""S1"", ""C1""]",['C1'],G1 = S1/2\nG2 = G1*W\nS2 = S1 * W\nT = S2 + G2...,NaN,"{""S2 = S1 * W"": ""The total number of tomatoes ...","{""S1"": ""Number of tomatoes Steve eats per day""...",S1 = 6\nV1 = 3\nC1 = 20\nW = 7\nG1 = 3.0\nS2 =...,4
1,1878,C1 = 20\nS1 = 6\nV1 = 3\nW = 7\nG1 = S1/2\nG2 ...,Variables:\nC1 = 20 [Number of cherries Steve ...,21,V1,3.0,"[""V1"", ""C1""]",['C1'],G1 = S1/2\nG2 = G1*W\nS2 = S1 * W\nT = S2 + G2...,NaN,"{""S2 = S1 * W"": ""The total number of tomatoes ...","{""S1"": ""Number of tomatoes Steve eats per day""...",S1 = 6\nV1 = 3\nC1 = 20\nW = 7\nG1 = 3.0\nS2 =...,1
2,1878,C1 = 20\nS1 = 6\nV1 = 3\nW = 7\nG1 = S1/2\nG2 ...,Variables:\nC1 = 20 [Number of cherries Steve ...,21,W,7.0,"[""W"", ""C1""]",['C1'],G1 = S1/2\nG2 = G1*W\nS2 = S1 * W\nT = S2 + G2...,NaN,"{""S2 = S1 * W"": ""The total number of tomatoes ...","{""S1"": ""Number of tomatoes Steve eats per day""...",S1 = 6\nV1 = 3\nC1 = 20\nW = 7\nG1 = 3.0\nS2 =...,3
3,1878,D = 0.5\nQ = 3\nT = 10\nW = 40\nB = S* T\nS = ...,Variables:\nB [Total number of gallons of bloo...,1200,W,40.0,"[""W"", ""D""]",['D'],B = S* T\nS = Q * W\nT = 10\nQ = 3\nWhat is B?,NaN,"{""S = Q * W"": ""The amount of blood in one shar...","{""W"": ""Number of gallons of blood in one whale...",W = 40\nT = 10\nQ = 3\nD = 0.5\nS = 120\nB = 1200,2
4,1878,D = 0.5\nQ = 3\nT = 10\nW = 40\nB = S* T\nS = ...,Variables:\nB [Total number of gallons of bloo...,1200,T,10.0,"[""T"", ""D""]",['D'],B = S* T\nS = Q * W\nW = 40\nQ = 3\nWhat is B?,NaN,"{""S = Q * W"": ""The amount of blood in one shar...","{""W"": ""Number of gallons of blood in one whale...",W = 40\nT = 10\nQ = 3\nD = 0.5\nS = 120\nB = 1200,1

In [26]:
print(f'longest equation = {df_csp_full['Rewritten Problem'].apply(len).max()}')
print(f'shortest equation = {df_csp_full['Rewritten Problem'].apply(len).min()}')
print(f'average equation = {df_csp_full['Rewritten Problem'].apply(len).mean()}')

longest equation = 166
shortest equation = 22
average equation = 67.91048399332423

In [27]:
df_csp_pilot_prompts.head()

,Question ID,Full Problem,CSP,Full Answer,GT Question,Heldout Value,Possible Questions,Distractor Vars,Rewritten Problem,Rewritten Problem Answer,Equations,Variables,Pred Values,depth
0,9942,IR = 100\nT = 100\nB = (T - R) * 0.60\nR = T /...,Variables:\nB [No. of Blue Hats]\nIR = 100 [Pa...,20,T,100.0,"[""T"", ""IR""]",['IR'],B = (T - R) * 0.60\nR = T / 2\nW = T - R - B\n...,NaN,"{""R = T / 2"": ""No. of Red Hats is equal to Tot...","{""T"": ""Total no. of Hats"", ""R"": ""No. of Red Ha...",T = 100\nIR = 100\nR = 50.0\nB = 30.0\nW = 20.0,3
1,9942,A = 7\nB = 5\nC = 6\nC1 = 10\nM = 5\nP3 = 4\nS...,Variables:\nA = 7 [Total number of apples in t...,5,C,6.0,"[""C"", ""M"", ""W""]","['M', 'W']",P1= C1/B\nP2=2*P1\nP4=0.5*P3\nR=T-C1-C*P2-S*P3...,NaN,"{""P1= C1/B"": ""Cost per bacon is equal to the t...","{""B"": ""Total number of bacon in the Kelly's ca...",B = 5\nC1 = 10\nM = 5\nC = 6\nS = 3\nP3 = 4\nA...,1
2,9942,M = 12\nR = 20\nV = 1\nY = 10\nN = 1.4 * R\nT ...,Variables:\nM = 12 [Number of months per year]...,5760,M,12.0,"[""M"", ""V""]",['V'],N = 1.4 * R\nT = TR + TN\nTN = N * M * Y\nTR =...,NaN,"{""N = 1.4 * R"": ""Number of coins Neil saves pe...","{""R"": ""Number of coins Rong saves per month"", ...",R = 20\nV = 1\nM = 12\nY = 10\nN = 28.0\nTR = ...,2
3,9942,C = 20\nCC = 5\nIR = 1200\nL = 10\nM = 1000\nT...,Variables:\nB [Total no. of bills with Thomas]...,240,M,1000.0,"[""M"", ""IR""]",['IR'],B = (M / C) - L\nR = B / 2\nR1 = B - R\nTB = T...,NaN,"{""B = (M / C) - L"": ""Total no. of bills with T...","{""M"": ""Total money withdrawn"", ""C"": ""Denominat...",M = 1000\nC = 20\nL = 10\nT = 3\nCC = 5\nIR = ...,5
4,9942,B0 = 0.5\nC0 = 0.3\nK = 22\nT = 100\nA1=0.2*10...,Variables:\nA1 [Total number of vote gotten by...,50,T,100.0,"[""T"", ""B0"", ""C0"", ""K""]","['B0', 'C0', 'K']",A1=0.2*100\nB1=A1+(0.5*A1)\nC1=T-A1-B1\nWhat i...,NaN,"{""A1=0.2*100"": ""Total number of vote gotten by...","{""A1"": ""Total number of vote gotten by Candida...",B0 = 0.5\nC0 = 0.3\nT = 100\nK = 22\nA1 = 20.0...,1

In [28]:
df_csp_pilot.head()

,Question ID,Full Problem,CSP,Full Answer,GT Question,Heldout Value,Possible Questions,Distractor Vars,Rewritten Problem,Rewritten Problem Answer,Equations,Variables,Pred Values,depth
0,5886,F = 0.5\nS = 0.3\nT = 22\nV = 100\nA = 0.2 * V...,Variables:\nA [Number of votes Candidate A rec...,50,V,100.0,"[""V"", ""F"", ""S"", ""T""]","['F', 'S', 'T']",A = 0.2 * V\nB = A + (0.5 * A)\nC = V - (A + B...,NaN,"{""A = 0.2 * V"": ""The number of votes Candidate...","{""A"": ""Number of votes Candidate A received"", ...",F = 0.5\nS = 0.3\nV = 100\nT = 22\nA = 20.0\nB...,3
1,5886,R1 = 0.5\nR2 = 0.3\nR3 = 22\nV = 100\nA = 0.2 ...,Variables:\nA [Total number of votes received ...,50,V,100.0,"[""V"", ""R1"", ""R2"", ""R3""]","['R1', 'R2', 'R3']",A = 0.2 * V\nB = A + (0.5 * A)\nC = V - A - B\...,NaN,"{""A = 0.2 * V"": ""Total no. of votes received b...","{""A"": ""Total number of votes received by Candi...",V = 100\nR1 = 0.5\nR2 = 0.3\nR3 = 22\nA = 20.0...,3
2,5886,A1 = 26\nA2 = 14\nAD = 2\nC1 = 12\nC2 = 10\nCA...,Variables:\nA1 = 26 [Fee for each adult at the...,28,A1,26.0,"[""A1"", ""CAR1""]",['CAR1'],S = T1-T2\nT1 = (A1 * AD) + (C1 * CH)\nT2 = (A...,NaN,"{""T1 = (A1 * AD) + (C1 * CH)"": ""Total cost for...","{""A1"": ""Fee for each adult at the first amusem...",A1 = 26\nC1 = 12\nCAR1 = 5\nA2 = 14\nC2 = 10\n...,2
3,5886,A1 = 26\nA2 = 14\nAD = 2\nC1 = 12\nC2 = 10\nCA...,Variables:\nA1 = 26 [Fee for each adult at the...,28,C1,12.0,"[""C1"", ""CAR1""]",['CAR1'],S = T1-T2\nT1 = (A1 * AD) + (C1 * CH)\nT2 = (A...,NaN,"{""T1 = (A1 * AD) + (C1 * CH)"": ""Total cost for...","{""A1"": ""Fee for each adult at the first amusem...",A1 = 26\nC1 = 12\nCAR1 = 5\nA2 = 14\nC2 = 10\n...,2
4,5886,A1 = 26\nA2 = 14\nAD = 2\nC1 = 12\nC2 = 10\nCA...,Variables:\nA1 = 26 [Fee for each adult at the...,28,A2,14.0,"[""A2"", ""CAR1""]",['CAR1'],S = T1-T2\nT1 = (A1 * AD) + (C1 * CH)\nT2 = (A...,NaN,"{""T1 = (A1 * AD) + (C1 * CH)"": ""Total cost for...","{""A1"": ""Fee for each adult at the first amusem...",A1 = 26\nC1 = 12\nCAR1 = 5\nA2 = 14\nC2 = 10\n...,2

In [29]:
df_verbal_full_prompts.head()

,CSP,Full Answer,GT Question,Possible Questions,Heldout Constraint,Rewritten Problem,Rewritten Problem Answer,Equations,Variables,depth,Question ID
0,Variables:\n* E1 [Earnings from regular hours]...,460.0,R,"[""R"", ""H3""]",R = 10 [Eliza's regular hourly rate]\nH3 = 2 [...,Eliza's rate per hour for the first 40 hours s...,Unclear,"{""E1 = R * H1"": ""Earnings from regular hours i...","{""E1"": ""Earnings from regular hours"", ""E2"": ""E...",2,78
1,Variables:\n* E1 [Earnings from regular hours]...,460.0,H1,"[""H1"", ""H3""]",H1 = 40 [Hours worked at the regular rate]\nH3...,Eliza's rate per hour for each week is $10. Sh...,Unclear,"{""E1 = R * H1"": ""Earnings from regular hours i...","{""E1"": ""Earnings from regular hours"", ""E2"": ""E...",2,78
2,Variables:\n* E1 [Earnings from regular hours]...,460.0,R,"[""R"", ""H3""]",R = 10 [Eliza's regular hourly rate]\nH3 = 2 [...,Eliza's rate per hour for the first 40 hours. ...,Unclear,"{""E1 = R * H1"": ""Earnings from regular hours i...","{""E1"": ""Earnings from regular hours"", ""E2"": ""E...",2,78
3,Variables:\n* E1 [Earnings from regular hours]...,460.0,H1,"[""H1"", ""H3""]",H1 = 40 [Hours worked at the regular rate]\nH3...,she works each week is $10. She also receives ...,Unclear,"{""E1 = R * H1"": ""Earnings from regular hours i...","{""E1"": ""Earnings from regular hours"", ""E2"": ""E...",2,78
4,Variables:\n* E1 [Earnings from regular hours]...,460.0,H4,"[""H4"", ""H3""]",H4 = 1 [Paid lunch hours]\nH3 = 2 [Unpaid trai...,Eliza's rate per hour for the first 40 hours s...,Unclear,"{""E1 = R * H1"": ""Earnings from regular hours i...","{""E1"": ""Earnings from regular hours"", ""E2"": ""E...",2,78

In [30]:
df_verbal_full.head()

,CSP,Full Answer,GT Question,Possible Questions,Heldout Constraint,Rewritten Problem,Rewritten Problem Answer,Equations,Variables,depth,Question ID
0,Variables:\n* C = 0.35 [Percentage upto which ...,160.0,F,"[""F"", ""C""]",F = 200 [Total size of the file to be download...,Carla is downloading a file. Normally she can ...,Unclear,"{""T = T1 + R + T3"": ""The total time to downloa...","{""C"": ""Percentage upto which the company takes...",2,62
1,Variables:\n* C = 0.35 [Percentage upto which ...,160.0,S,"[""S"", ""C""]",S = 2 [Normal download speed]\nC = 0.35 [Perce...,Carla is downloading a 200 GB file. 40% of the...,Unclear,"{""T = T1 + R + T3"": ""The total time to downloa...","{""C"": ""Percentage upto which the company takes...",2,62
2,Variables:\n* C = 0.35 [Percentage upto which ...,160.0,P1,"[""P1"", ""C""]",P1 = 0.4 [Percentage of the file downloaded be...,Carla is downloading a 200 GB file. Normally s...,Unclear,"{""T = T1 + R + T3"": ""The total time to downloa...","{""C"": ""Percentage upto which the company takes...",2,62
3,Variables:\n* C = 0.35 [Percentage upto which ...,160.0,R,"[""R"", ""C""]",R = 20 [Time taken for the forced restart and ...,Carla is downloading a 200 GB file. Normally s...,Unclear,"{""T = T1 + R + T3"": ""The total time to downloa...","{""C"": ""Percentage upto which the company takes...",1,62
4,Variables:\n* B = 30000 [Base price of the tru...,43500.0,B,"[""B"", ""X1"", ""X2""]",B = 30000 [Base price of the truck in dollars]...,Bill is ordering a new truck for his construct...,Unclear,"{""L = K / F1"": ""Leather seats cost is one-thir...","{""B"": ""Base price of the truck in dollars"", ""E...",1,5126

In [31]:
df_verbal_pilot_prompts.head()

,CSP,Full Answer,GT Question,Possible Questions,Heldout Constraint,Rewritten Problem,Rewritten Problem Answer,Equations,Variables,depth,Question ID
0,Variables:\n* B [Number of emails sent to her ...,1,W,"[""W""]",W = 7 [Number of emails which are work related],Robyn sends sixteen emails a day. She also sen...,Unclear,"{""B = 1/3 * R2"": ""The number of emails sent to...","{""B"": ""Number of emails sent to her boyfriend""...",4,7654
1,Variables:\n* A = 7 [Total number of apples in...,5,C1,"[""C1"", ""M"", ""W""]",C1 = 10 [Total cost of bacon.]\nM = 5 [Total c...,Kelly is grocery shopping at a supermarket and...,Unclear,"{""P1= C1/B"": ""Cost per bacon is equal to the t...","{""A"": ""Total number of apples in the Kelly's c...",3,7062
2,Variables:\n* A1 = 26 [Fee for each adult at t...,28,C2,"[""C2"", ""CAR1""]",C2 = 10 [Fee for each child at the second amus...,Jake's family wants to compare the cost of the...,Unclear,"{""S = T1-T2"": ""The amount saved by choosing th...","{""A1"": ""Fee for each adult at the first amusem...",2,5974
3,Variables:\n* C = 12 [Cost of cord for each cl...,1198,M,"[""M"", ""J""]",M = 2 [Number of seniors who are chess club me...,"In a school, there are 44 seniors. Each senior...",Unclear,"{""F2 = F1 + (E * F1)"": ""The final cost of the ...","{""C"": ""Cost of cord for each class officers"", ...",1,2958
4,Variables:\n* A [Total amount paid by you afte...,35,T,"[""T"", ""D""]",T = 0.2 [Tip rate on the discounted bill]\nD =...,My wife and I went out for dinner at a restaur...,Unclear,"{""A=S+P"": ""The total payment is your half of t...","{""A"": ""Total amount paid by you after adding t...",2,4318

In [32]:
df_verbal_pilot.head()

,CSP,Full Answer,GT Question,Possible Questions,Heldout Constraint,Rewritten Problem,Rewritten Problem Answer,Equations,Variables,depth,Question ID
0,Variables:\n* A = 20 [Tip amount per customer ...,1520,N,"[""N"", ""L""]",N = 40 [Number of customers]\nL = 20 [Lipstick...,"While working at the restaurant, each customer...",Unclear,"{""J = R - (0.1 * R)"": ""The total tips received...","{""A"": ""Tip amount per customer for Rafaela"", ""...",3,6878
1,Variables:\n* A = 20 [Tip amount per customer ...,1520,A,"[""A"", ""L""]",A = 20 [Tip amount per customer for Rafaela]\n...,"While working at the restaurant, forty custome...",Unclear,"{""J = R - (0.1 * R)"": ""The total tips received...","{""A"": ""Tip amount per customer for Rafaela"", ""...",3,6878
2,Variables:\n* M = 12 [Number of months per yea...,5760,R,"[""R"", ""V""]",R = 20 [Number of coins Rong saves per month]\...,Rong has been saving in his piggy bank every m...,Unclear,"{""N = 1.4 * R"": ""Number of coins Neil saves pe...","{""M"": ""Number of months per year"", ""N"": ""Numbe...",3,5526
3,Variables:\n* M = 12 [Number of months per yea...,5760,Y,"[""Y"", ""V""]",Y = 10 [Number of years]\nV = 1 [Value of each...,Rong has been saving 20 coins in his piggy ban...,Unclear,"{""N = 1.4 * R"": ""Number of coins Neil saves pe...","{""M"": ""Number of months per year"", ""N"": ""Numbe...",2,5526
4,Variables:\n* F1 = 20 [Number of times the fir...,175,F1,"[""F1"", ""P""]",F1 = 20 [Number of times the first friend pres...,"On a particular day, Jerome had 4 friends who ...",Unclear,"{""F2 = F1 + ((1 / 4) * F1 )"": ""The number of t...","{""F1"": ""Number of times the first friend press...",2,806