In [1]:
import pandas as pd
import tokenizers

df = pd.read_csv("questbench_data/GSM-Q/gsm_CSP_full.csv")

In [2]:
df.head()

,Question ID,Full Problem,CSP,Full Answer,GT Question,Heldout Value,Possible Questions,Distractor Vars,Rewritten Problem,Rewritten Problem Answer,Equations,Variables,Pred Values,depth
0,1878,C1 = 20\nS1 = 6\nV1 = 3\nW = 7\nG1 = S1/2\nG2 ...,Variables:\nC1 = 20 [Number of cherries Steve ...,21,S1,6.0,"[""S1"", ""C1""]",['C1'],G1 = S1/2\nG2 = G1*W\nS2 = S1 * W\nT = S2 + G2...,NaN,"{""S2 = S1 * W"": ""The total number of tomatoes ...","{""S1"": ""Number of tomatoes Steve eats per day""...",S1 = 6\nV1 = 3\nC1 = 20\nW = 7\nG1 = 3.0\nS2 =...,4
1,1878,C1 = 20\nS1 = 6\nV1 = 3\nW = 7\nG1 = S1/2\nG2 ...,Variables:\nC1 = 20 [Number of cherries Steve ...,21,V1,3.0,"[""V1"", ""C1""]",['C1'],G1 = S1/2\nG2 = G1*W\nS2 = S1 * W\nT = S2 + G2...,NaN,"{""S2 = S1 * W"": ""The total number of tomatoes ...","{""S1"": ""Number of tomatoes Steve eats per day""...",S1 = 6\nV1 = 3\nC1 = 20\nW = 7\nG1 = 3.0\nS2 =...,1
2,1878,C1 = 20\nS1 = 6\nV1 = 3\nW = 7\nG1 = S1/2\nG2 ...,Variables:\nC1 = 20 [Number of cherries Steve ...,21,W,7.0,"[""W"", ""C1""]",['C1'],G1 = S1/2\nG2 = G1*W\nS2 = S1 * W\nT = S2 + G2...,NaN,"{""S2 = S1 * W"": ""The total number of tomatoes ...","{""S1"": ""Number of tomatoes Steve eats per day""...",S1 = 6\nV1 = 3\nC1 = 20\nW = 7\nG1 = 3.0\nS2 =...,3
3,1878,D = 0.5\nQ = 3\nT = 10\nW = 40\nB = S* T\nS = ...,Variables:\nB [Total number of gallons of bloo...,1200,W,40.0,"[""W"", ""D""]",['D'],B = S* T\nS = Q * W\nT = 10\nQ = 3\nWhat is B?,NaN,"{""S = Q * W"": ""The amount of blood in one shar...","{""W"": ""Number of gallons of blood in one whale...",W = 40\nT = 10\nQ = 3\nD = 0.5\nS = 120\nB = 1200,2
4,1878,D = 0.5\nQ = 3\nT = 10\nW = 40\nB = S* T\nS = ...,Variables:\nB [Total number of gallons of bloo...,1200,T,10.0,"[""T"", ""D""]",['D'],B = S* T\nS = Q * W\nW = 40\nQ = 3\nWhat is B?,NaN,"{""S = Q * W"": ""The amount of blood in one shar...","{""W"": ""Number of gallons of blood in one whale...",W = 40\nT = 10\nQ = 3\nD = 0.5\nS = 120\nB = 1200,1

In [3]:
df[df.depth == 1]

,Question ID,Full Problem,CSP,Full Answer,GT Question,Heldout Value,Possible Questions,Distractor Vars,Rewritten Problem,Rewritten Problem Answer,Equations,Variables,Pred Values,depth
1,1878,C1 = 20\nS1 = 6\nV1 = 3\nW = 7\nG1 = S1/2\nG2 ...,Variables:\nC1 = 20 [Number of cherries Steve ...,21,V1,3.0,"[""V1"", ""C1""]",['C1'],G1 = S1/2\nG2 = G1*W\nS2 = S1 * W\nT = S2 + G2...,NaN,"{""S2 = S1 * W"": ""The total number of tomatoes ...","{""S1"": ""Number of tomatoes Steve eats per day""...",S1 = 6\nV1 = 3\nC1 = 20\nW = 7\nG1 = 3.0\nS2 =...,1
4,1878,D = 0.5\nQ = 3\nT = 10\nW = 40\nB = S* T\nS = ...,Variables:\nB [Total number of gallons of bloo...,1200,T,10.0,"[""T"", ""D""]",['D'],B = S* T\nS = Q * W\nW = 40\nQ = 3\nWhat is B?,NaN,"{""S = Q * W"": ""The amount of blood in one shar...","{""W"": ""Number of gallons of blood in one whale...",W = 40\nT = 10\nQ = 3\nD = 0.5\nS = 120\nB = 1200,1
8,1878,D = 0.5\nM = 3\nN = 10\nW = 40\nS = M * W\nT =...,Variables:\nD = 0.5 [Fraction for dolphin's bl...,1200,N,10.0,"[""N"", ""D""]",['D'],S = M * W\nT = N * S\nW = 40\nM = 3\nWhat is T?,NaN,"{""S = M * W"": ""The blood volume of a shark is ...","{""W"": ""Gallons of blood in a whale"", ""M"": ""Mul...",W = 40\nM = 3\nD = 0.5\nN = 10\nS = 120\nT = 1200,1
10,1878,BV = 3\nD = 20\nN = 10\nW = 40\nS = BV* W\nT =...,Variables:\nBV = 3 [Blood volume of shark vs w...,1200,N,10.0,"[""N"", ""D""]",['D'],S = BV* W\nT = N * S\nW = 40\nBV = 3\nWhat is T?,NaN,"{""S = BV* W"": ""Blood volume of one shark is th...","{""W"": ""Blood volume of one whale in gallons"", ...",W = 40\nN = 10\nD = 20\nBV = 3\nS = 120\nT = 1200,1
15,1878,B = 10\nM = 2.5\nN1 = 10\nN2 = 6\nP = 0.1\nR =...,Variables:\nB = 10 [Amount Carl pays with in ...,4,B,10.0,"[""B"", ""M""]",['M'],R = B - T\nT = N1 * N2 * P\nN1 = 10\nN2 = 6\nP...,NaN,"{""T = N1 * N2 * P"": ""The total cost of the coo...","{""N1"": ""Number of packs of cookies Carl buys"",...",N1 = 10\nN2 = 6\nP = 0.1\nM = 2.5\nB = 10\nT =...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6575,1878,A = 90\nB = 0.5\nD = 20\nE = 60\nG = 10\nC = A...,Variables:\nA = 90 [Total number of rooms]\nB ...,15,E,60.0,"[""E"", ""G""]",['G'],C = A * B\nF = (C * D) / E\nA = 90\nB = 0.5\nD...,NaN,"{""C = A * B"": ""Number of rooms to be cleaned i...","{""A"": ""Total number of rooms"", ""B"": ""Fraction ...",A = 90\nB = 0.5\nD = 20\nE = 60\nG = 10\nC = 4...,1
6578,1878,E = 5\nM = 4\nP = 20\nX = 2\nT1=P-M\nT2=T1/X\n...,Variables:\nE = 5 [Number of erasers added to ...,8,X,2.0,"[""X"", ""E""]",['E'],T1=P-M\nT2=T1/X\nP = 20\nM = 4\nWhat is T2?,NaN,"{""T1=P-M"": ""Total number of pencils in the box...","{""P"": ""Number of pencils in one box"", ""M"": ""Nu...",P = 20\nM = 4\nE = 5\nX = 2\nT1 = 16\nT2 = 8.0,1
6579,1878,A = 20\nB = 4\nC = 5\nP = 2\nX=(A-B)/P\nWhat i...,Variables:\nA = 20 [The number of pencils box ...,8,A,20.0,"[""A"", ""C""]",['C'],X=(A-B)/P\nB = 4\nP = 2\nWhat is X?,NaN,"{""X=(A-B)/P"": ""The number of pairs of pencils ...","{""A"": ""The number of pencils box can hold"", ""B...",A = 20\nB = 4\nC = 5\nP = 2\nX = 8.0,1
6580,1878,A = 20\nB = 4\nC = 5\nP = 2\nX=(A-B)/P\nWhat i...,Variables:\nA = 20 [The number of pencils box ...,8,B,4.0,"[""B"", ""C""]",['C'],X=(A-B)/P\nA = 20\nP = 2\nWhat is X?,NaN,"{""X=(A-B)/P"": ""The number of pairs of pencils ...","{""A"": ""The number of pencils box can hold"", ""B...",A = 20\nB = 4\nC = 5\nP = 2\nX = 8.0,1
6581,1878,A = 20\nB = 4\nC = 5\nP = 2\nX=(A-B)/P\nWhat i...,Variables:\nA = 20 [The number of pencils box ...,8,P,2.0,"[""P"", ""C""]",['C'],X=(A-B)/P\nA = 20\nB = 4\nWhat is X?,NaN,"{""X=(A-B)/P"": ""The number of pairs of pencils ...","{""A"": ""The number of pencils box can hold"", ""B...",A = 20\nB = 4\nC = 5\nP = 2\nX = 8.0,1

In [4]:
len(df["Full Problem"]) == len(df["Full Problem"].unique())

False

In [5]:
len(df["Full Problem"])

6591

In [6]:
 len(df["Full Problem"].unique())

1660

In [7]:
df_d_1 = df[df.depth == 1]

In [8]:
len(df_d_1["Full Problem"]) == len(df_d_1["Full Problem"].unique())

False

In [9]:
len(df_d_1["Full Problem"])

1560

In [10]:
len(df_d_1["Full Problem"].unique())

1066

In [11]:
print(df["Full Problem"][0])

C1 = 20
S1 = 6
V1 = 3
W = 7
G1 = S1/2
G2 = G1*W
S2 = S1 * W
T = S2 + G2
V = T/V1
What is V?

In [12]:
print(df["Rewritten Problem"][2])

G1 = S1/2
G2 = G1*W
S2 = S1 * W
T = S2 + G2
V = T/V1
S1 = 6
V1 = 3
What is V?

In [13]:
import numpy as np

special_tokens = [
    "[PAD]", 
    "[UNK]", 
    "<BOP>", # begining of problem
    "<EOP>", # end of problem
    "<BOQ>", # begining of questions
    "<EOQ>", # end of questions
]

full_problems = np.concat(df["Full Problem"].apply(set).apply(list).values)
questions = np.concat(df["Possible Questions"].apply(set).apply(list).values)

vocabulary = set(np.concat([full_problems, questions, special_tokens]))
vocab_size = len(vocabulary)

In [14]:
print(df["Rewritten Problem"].apply(lambda x: f"<BOP>{x}".replace("What is", "<EOP><BOQ>").replace("?", "<EOQ>"))[0])

<BOP>G1 = S1/2
G2 = G1*W
S2 = S1 * W
T = S2 + G2
V = T/V1
V1 = 3
W = 7
<EOP><BOQ> V<EOQ>

In [15]:
vocab_size

77

In [16]:
data = list(df["Full Problem"].values) + list(df["Possible Questions"].values)
data[:5]

['C1 = 20\nS1 = 6\nV1 = 3\nW = 7\nG1 = S1/2\nG2 = G1*W\nS2 = S1 * W\nT = S2 + G2\nV = T/V1\nWhat is V?',
 'C1 = 20\nS1 = 6\nV1 = 3\nW = 7\nG1 = S1/2\nG2 = G1*W\nS2 = S1 * W\nT = S2 + G2\nV = T/V1\nWhat is V?',
 'C1 = 20\nS1 = 6\nV1 = 3\nW = 7\nG1 = S1/2\nG2 = G1*W\nS2 = S1 * W\nT = S2 + G2\nV = T/V1\nWhat is V?',
 'D = 0.5\nQ = 3\nT = 10\nW = 40\nB = S* T\nS = Q * W\nWhat is B?',
 'D = 0.5\nQ = 3\nT = 10\nW = 40\nB = S* T\nS = Q * W\nWhat is B?']

In [17]:
from tokenizers import Tokenizer, AddedToken
from tokenizers.models import WordLevel
from tokenizers.trainers import WordLevelTrainer
from tokenizers import pre_tokenizers

tokenizer = Tokenizer(WordLevel(unk_token="[UNK]"))

tokenizer.add_special_tokens([
    AddedToken(t, single_word=False, lstrip=False, rstrip=False, normalized=False)
    for t in ["<BOP>", "<EOP>", "<BOQ>", "<EOQ>"]
])

tokenizer.pre_tokenizer = pre_tokenizers.Split("", behavior="isolated")

trainer = WordLevelTrainer(
    min_frequency=1,
    special_tokens=special_tokens
)


tokenizer.train_from_iterator(data, trainer)

tokenizer.enable_padding(
    pad_token="[PAD]",
    pad_id=tokenizer.token_to_id("[PAD]")
)

In [18]:
enc = tokenizer.encode(
    df["Rewritten Problem"].apply(
        lambda x: f"<BOP>{x}".replace("What is", "<EOP><BOQ>").replace("?", "<EOQ>"))[0]
)
print(enc.tokens)

['<BOP>', 'G', '1', ' ', '=', ' ', 'S', '1', '/', '2', '\n', 'G', '2', ' ', '=', ' ', 'G', '1', '*', 'W', '\n', 'S', '2', ' ', '=', ' ', 'S', '1', ' ', '*', ' ', 'W', '\n', 'T', ' ', '=', ' ', 'S', '2', ' ', '+', ' ', 'G', '2', '\n', 'V', ' ', '=', ' ', 'T', '/', 'V', '1', '\n', 'V', '1', ' ', '=', ' ', '3', '\n', 'W', ' ', '=', ' ', '7', '\n', '<EOP>', '<BOQ>', ' ', 'V', '<EOQ>']

In [19]:
print(enc)

Encoding(num_tokens=72, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])

In [21]:
problems = df["Rewritten Problem"].astype(str).tolist()

problems_encoded = tokenizer.encode_batch(data)

In [22]:
questions = df["Possible Questions"].astype(str).tolist()

questions_encoded = tokenizer.encode_batch(questions)

In [23]:
df["Rewritten Problem"].astype(str).tolist()[0]

'G1 = S1/2\nG2 = G1*W\nS2 = S1 * W\nT = S2 + G2\nV = T/V1\nV1 = 3\nW = 7\nWhat is V?'

In [28]:
problems_encoded[0].tokens[:5]

['C', '1', ' ', '=', ' ']

In [27]:
df["Possible Questions"].astype(str).tolist()[0]

'["S1", "C1"]'

In [29]:
questions_encoded[0].tokens[:5]

['[', '"', 'S', '1', '"']